<template>
  <div class="test">
    <el-container>
      <el-header>
        <h2>header</h2>
      </el-header>
      <el-main>
        <h2>main</h2>
        <h2>main</h2>
        <h2>main</h2>
        <h2>main</h2>
        <h2>main</h2>
        <h2>main</h2>
        <h2>main</h2>
        <h2>main</h2>
        <h2>main</h2>
        <h2>main</h2>
        <h2>main</h2>
        <h2>main</h2>
        <h2>main</h2>
        <h2>main</h2>
        <h2>main</h2>
        <h2>main</h2>
        <h2>main</h2>
        <h2>main</h2>
        <h2>main</h2>
        <h2>main</h2>
        <h2>main</h2>
        <h2>main</h2>
        <h2>main</h2>
        <h2>main</h2>
      </el-main>
      <el-footer>
        <h2>footer</h2>
      </el-footer>
    </el-container>
  </div>
</template>
<script>
export default {
  name: 'Test'
}
</script>
<style>
  html,body{
    margin:0;
  }
</style>
